# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_app', '0001_initial'),
        ('sucursal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoInternoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido de Traspaso')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO_PENDIENTE_VERIFICACION', 'Recibido, Pendiente de Verificación'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=35, verbose_name='Estado del Traspaso')),
                ('motivo', models.CharField(choices=[('REABASTECIMIENTO', 'Reabastecimiento'), ('TRASPASO_DIRECTO', 'Traspaso Directo'), ('PARA_COMPLETAR_PEDIDO', 'Para Completar Pedido Cliente'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario'), ('OTRO', 'Otro')], max_length=30, verbose_name='Motivo del Traspaso')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Adicionales')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
            ],
            options={
                'verbose_name': 'Traspaso Interno de Stock',
                'verbose_name_plural': 'Traspasos Internos de Stock',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspasoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_enviada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Enviada')),
                ('cantidad_recibida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Recibida')),
                ('bodega_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_recibidos_en', to='sucursal_app.bodega', verbose_name='Bodega de Destino del Ítem')),
                ('bodega_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_traspasados_desde', to='sucursal_app.bodega', verbose_name='Bodega de Origen del Ítem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_app.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Traspaso de Stock',
                'verbose_name_plural': 'Detalles de Traspasos de Stock',
            },
        ),
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Inventario')),
                ('ultima_actualizacion_general', models.DateTimeField(auto_now=True, verbose_name='Última Actualización General')),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_general', to='sucursal_app.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Inventario de Sucursal',
                'verbose_name_plural': 'Inventarios de Sucursal',
                'ordering': ['sucursal__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleInventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('stock_minimo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Máximo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='sucursal_app.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_en_bodegas', to='producto_app.producto')),
                ('inventario_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_bodega', to='inventario_app.inventariosucursal')),
            ],
            options={
                'verbose_name': 'Detalle de Stock en Bodega',
                'verbose_name_plural': 'Detalles de Stock en Bodega',
                'ordering': ['inventario_sucursal', 'bodega', 'producto'],
            },
        ),
    ]
