# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_app', '0001_initial'),
        ('pedido_app', '0001_initial'),
        ('sucursal_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasointernostock',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='traspasointernostock',
            name='pedido_cliente_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_generados', to='pedido_app.pedidocliente', verbose_name='Pedido Cliente Origen (Automático)'),
        ),
        migrations.AddField(
            model_name='traspasointernostock',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_destino', to='sucursal_app.sucursal', verbose_name='Sucursal de Destino'),
        ),
        migrations.AddField(
            model_name='traspasointernostock',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_origen', to='sucursal_app.sucursal', verbose_name='Sucursal de Origen'),
        ),
        migrations.AddField(
            model_name='detalletraspasostock',
            name='traspaso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_traspaso', to='inventario_app.traspasointernostock', verbose_name='Traspaso Asociado'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleinventariobodega',
            unique_together={('inventario_sucursal', 'producto', 'bodega')},
        ),
        migrations.AlterUniqueTogether(
            name='detalletraspasostock',
            unique_together={('traspaso', 'producto')},
        ),
    ]
