# Generated by Django 5.2.2 on 2025-06-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_app', '0001_initial'),
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_calle_numero',
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias de la Dirección (ej: Casa, Oficina)')),
                ('direccion_calle_numero', models.CharField(max_length=255, verbose_name='Dirección (Calle y Número)')),
                ('informacion_adicional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Adicional (ej: Depto, Casa)')),
                ('es_principal', models.BooleanField(default=False, help_text='Marca esta casilla si esta es tu dirección de envío por defecto.', verbose_name='¿Es la dirección principal?')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuario_app.cliente', verbose_name='Cliente')),
                ('sucursal_favorita', models.ForeignKey(blank=True, help_text='Selecciona tu sucursal preferida para retiros o para ver stock local.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_preferentes', to='sucursal_app.sucursal', verbose_name='Sucursal Favorita')),
            ],
        ),
    ]
