# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Ferremas', max_length=150, verbose_name='Nombre de la Empresa')),
                ('rut_empresa', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT de la Empresa')),
                ('direccion_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Principal de la Empresa')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto Principal')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto Principal')),
                ('logo_empresa', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo de la Empresa')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, help_text='Valor porcentual del IVA. Ej: 19.00 para 19%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de IVA (%)')),
                ('monto_minimo_despacho_gratuito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mínimo para Despacho Gratuito')),
                ('url_terminos_condiciones', models.URLField(blank=True, null=True, verbose_name='URL Términos y Condiciones')),
                ('url_politica_privacidad', models.URLField(blank=True, null=True, verbose_name='URL Política de Privacidad')),
                ('modo_mantenimiento', models.BooleanField(default=False, verbose_name='Activar Modo Mantenimiento')),
                ('mensaje_mantenimiento', models.TextField(blank=True, null=True, verbose_name='Mensaje de Modo Mantenimiento')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración Global del Sistema',
                'verbose_name_plural': 'Configuraciones Globales del Sistema',
            },
        ),
    ]
