# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Bodega')),
            ],
            options={
                'verbose_name': 'Tipo de Bodega',
                'verbose_name_plural': 'Tipos de Bodega',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Sucursal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales_comuna', to='ubicacion_app.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales_region', to='ubicacion_app.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(help_text='Dirección específica de la bodega si es diferente a la sucursal o para identificarla.', max_length=255, verbose_name='Dirección de Bodega')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='sucursal_app.sucursal', verbose_name='Sucursal')),
                ('tipo_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_tipo', to='sucursal_app.tipobodega', verbose_name='Tipo de Bodega')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['sucursal__nombre', 'tipo_bodega__tipo'],
            },
        ),
    ]
