# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finanza_app', '0001_initial'),
        ('pedido_app', '0002_initial'),
        ('proveedor_app', '0001_initial'),
        ('usuario_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='usuario_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='pedido_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_cobrar', to='pedido_app.pedidocliente', verbose_name='Pedido de Cliente Asociado'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='pedido_proveedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='pedido_app.pedidoproveedor', verbose_name='Pedido a Proveedor Asociado'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='proveedor_app.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='documentofinanciero',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('cliente', 'proveedor')}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documentofinanciero',
            name='pedido_cliente_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_financieros', to='pedido_app.pedidocliente'),
        ),
        migrations.AddField(
            model_name='documentofinanciero',
            name='pedido_proveedor_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_financieros', to='pedido_app.pedidoproveedor'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='cuenta_bancaria_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanza_app.cuentabancaria', verbose_name='Cuenta Bancaria Asociada (si aplica)'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable'),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='cuenta_por_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanza_app.cuentaporpagar', verbose_name='Cuenta por Pagar Asociada'),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='proveedor_app.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='usuario_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='cuenta_por_cobrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanza_app.cuentaporcobrar', verbose_name='Cuenta por Cobrar Asociada'),
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
