# Generated by Django 5.2.2 on 2025-06-08 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Reporte Configurado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Reporte')),
                ('categoria', models.CharField(choices=[('VENTAS', 'Reportes de Ventas'), ('FINANZAS', 'Reportes de Finanzas'), ('COMPRAS', 'Reportes de Compras'), ('INVENTARIO', 'Reportes de Inventario'), ('CLIENTES', 'Reportes de Clientes'), ('PROVEEDORES', 'Reportes de Proveedores'), ('PERSONAL', 'Reportes de Personal/Usuarios'), ('OTRO', 'Otro Tipo de Reporte')], max_length=20, verbose_name='Categoría del Reporte')),
                ('tipo_especifico', models.CharField(blank=True, help_text='Identificador interno para la lógica de generación del reporte.', max_length=100, null=True, verbose_name='Tipo Específico de Reporte')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros de Configuración (JSON)')),
                ('formato_salida_preferido', models.CharField(choices=[('PANTALLA', 'Visualización en Pantalla'), ('CSV', 'Archivo CSV'), ('PDF', 'Archivo PDF'), ('EXCEL', 'Archivo Excel')], default='PANTALLA', max_length=10, verbose_name='Formato de Salida Preferido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_configurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Configurado',
                'verbose_name_plural': 'Reportes Configurados',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
