# Generated by Django 5.2.2 on 2025-06-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApiExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_integracion', models.CharField(help_text='Ej: Webpay, Chilexpress, Correo Electrónico SMTP', max_length=100, unique=True, verbose_name='Nombre de la Integración')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('PAGO', 'Pasarela de Pago'), ('ENVIO', 'Servicio de Envío'), ('ERP', 'Sistema ERP'), ('NOTIFICACION', 'Servicio de Notificación'), ('OTRO', 'Otro Tipo')], default='OTRO', max_length=20, verbose_name='Tipo de Integración')),
                ('base_url', models.URLField(blank=True, null=True, verbose_name='URL Base de la API')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key / Usuario')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Secret / Contraseña / Token')),
                ('configuracion_adicional', models.JSONField(blank=True, default=dict, null=True, verbose_name='Configuración Adicional (JSON)')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de API Externa',
                'verbose_name_plural': 'Configuraciones de APIs Externas',
                'ordering': ['nombre_integracion'],
            },
        ),
    ]
