# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_REABASTECIMIENTO', 'Pendiente de Reabastecimiento'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO_STOCK', 'Rechazado por Falta de Stock'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=30, verbose_name='Estado del Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Total Aplicado')),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impuesto Total')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total del Pedido')),
                ('metodo_envio', models.CharField(choices=[('RETIRO_TIENDA', 'Retiro en Tienda'), ('DESPACHO_DOMICILIO', 'Despacho a Domicilio')], max_length=30, verbose_name='Método de Envío')),
                ('direccion_entrega_texto', models.TextField(blank=True, null=True, verbose_name='Dirección de Entrega (si aplica)')),
                ('telefono_contacto_envio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto para Envío')),
                ('email_contacto_envio', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto para Envío')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del Cliente')),
                ('estado_preparacion', models.CharField(choices=[('PENDIENTE_ASIGNACION', 'Pendiente de Asignación'), ('ASIGNADO', 'Asignado para Preparación'), ('EN_PREPARACION', 'En Preparación'), ('LISTO_PARA_ENTREGA', 'Listo para Entrega/Despacho')], default='PENDIENTE_ASIGNACION', max_length=30, verbose_name='Estado de Preparación en Bodega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
            ],
            options={
                'verbose_name': 'Pedido de Cliente',
                'verbose_name_plural': 'Pedidos de Clientes',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO_PARCIAL', 'Recibido Parcialmente'), ('RECIBIDO_COMPLETO', 'Recibido Completamente'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20, verbose_name='Estado del Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Total')),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impuesto Total')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total del Pedido')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción Completa')),
                ('numero_guia_despacho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Guía de Despacho/Factura')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
            ],
            options={
                'verbose_name': 'Pedido a Proveedor',
                'verbose_name_plural': 'Pedidos a Proveedores',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario de Venta')),
                ('precio_unitario_con_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario con Descuento')),
                ('descuento_total_linea', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento Total en Línea')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_app.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Cliente',
                'verbose_name_plural': 'Detalles de Pedidos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada')),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario de Compra')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_app.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido a Proveedor',
                'verbose_name_plural': 'Detalles de Pedidos a Proveedores',
            },
        ),
    ]
