# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido_app', '0001_initial'),
        ('proveedor_app', '0001_initial'),
        ('sucursal_app', '0001_initial'),
        ('ubicacion_app', '0001_initial'),
        ('usuario_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='bodeguero_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil_personal__rol': 'BODEGUERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente_asignados_bodega', to=settings.AUTH_USER_MODEL, verbose_name='Bodeguero Asignado'),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='usuario_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='comuna_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion_app.comuna', verbose_name='Comuna de Entrega'),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='creado_por_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Gestionado por (Personal)'),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='sucursal_despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_a_despachar', to='sucursal_app.sucursal', verbose_name='Sucursal de Despacho'),
        ),
        migrations.AddField(
            model_name='detallepedidocliente',
            name='pedido_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido_cliente', to='pedido_app.pedidocliente', verbose_name='Pedido Cliente Asociado'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='bodega_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_proveedor_a_recibir', to='sucursal_app.bodega', verbose_name='Bodega de Recepción'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_proveedor_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to='proveedor_app.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='detallepedidoproveedor',
            name='pedido_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='pedido_app.pedidoproveedor', verbose_name='Pedido Asociado'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedidocliente',
            unique_together={('pedido_cliente', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='detallepedidoproveedor',
            unique_together={('pedido_proveedor', 'producto')},
        ),
    ]
