# Generated by Django 5.2.2 on 2025-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='estado',
            field=models.CharField(choices=[('POR_CONFIRMAR', 'Por Confirmar'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_REABASTECIMIENTO', 'Pendiente de Reabastecimiento'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO_STOCK', 'Rechazado por Falta de Stock'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=30, verbose_name='Estado del Pedido'),
        ),
    ]
