# Generated by Django 5.2.2 on 2025-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_app', '0003_alter_pedidocliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='metodo_envio',
            field=models.CharField(choices=[('RETIRO_EN_TIENDA', 'Retiro en Tienda'), ('DESPACHO_DOMICILIO', 'Despacho a Domicilio')], max_length=30, verbose_name='Método de Envío'),
        ),
    ]
