# Generated by Django 5.2.2 on 2025-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_app', '0004_alter_pedidocliente_metodo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='metodo_envio',
            field=models.CharField(choices=[('RETIRO_TIENDA', 'Retiro en Tienda'), ('DESPACHO_DOMICILIO', 'Despacho a Domicilio')], max_length=30, verbose_name='Método de Envío'),
        ),
    ]
