# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título de la Promoción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('tipo_promocion', models.CharField(choices=[('DESC_PORC', 'Descuento en Porcentaje (%)'), ('PRECIO_FIJO', 'Precio Fijo'), ('DESC_MONTO', 'Descuento de Monto Fijo ($)'), ('2X1', '2x1'), ('REGALO', 'Producto de Regalo')], max_length=20, verbose_name='Tipo de Promoción')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 20 para 20%, 10000 para precio fijo. Puede ser nulo para 2x1 o Regalo.', max_digits=10, null=True, verbose_name='Valor de la Promoción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Término')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID de la Entidad Objetivo')),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Promocional')),
                ('restricciones', models.TextField(blank=True, null=True, verbose_name='Restricciones y Condiciones')),
                ('limite_uso_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de Uso Total')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos Actuales')),
                ('solo_para_clientes_registrados', models.BooleanField(default=False, verbose_name='Solo para Clientes Registrados')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label__in': ['producto_app'], 'model__in': ['producto', 'categoria', 'marca']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Aplica a Tipo de Entidad')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio', 'titulo'],
            },
        ),
    ]
