# Generated by Django 5.2.2 on 2025-07-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0001_initial'),
        ('promocion_app', '0001_initial'),
        ('usuario_app', '0002_remove_cliente_direccion_calle_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='limite_uso_por_cliente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de Uso por Cliente'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto_regalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_como_regalo', to='producto_app.producto', verbose_name='Producto de Regalo (si aplica)'),
        ),
        migrations.CreateModel(
            name='UsoPromocionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usos', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Usos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_promociones', to='usuario_app.cliente')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_por_cliente', to='promocion_app.promocion')),
            ],
            options={
                'verbose_name': 'Uso de Promoción por Cliente',
                'verbose_name_plural': 'Usos de Promociones por Clientes',
                'unique_together': {('cliente', 'promocion')},
            },
        ),
    ]
