# Generated by Django 5.2.2 on 2025-06-25 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Pagado')),
                ('metodo_pago', models.CharField(choices=[('WEBPAY', 'Webpay Plus'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo (en tienda)'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('OTRO', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago')),
                ('id_transaccion_pasarela', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transacción Pasarela')),
                ('datos_adicionales_pasarela', models.JSONField(blank=True, null=True, verbose_name='Datos Adicionales de la Pasarela')),
                ('token_webpay_transaccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Transacción Webpay')),
                ('tipo_cuotas', models.CharField(blank=True, choices=[('SIN_CUOTAS', 'Sin Cuotas'), ('CUOTAS_NORMALES', 'Cuotas Normales'), ('CUOTAS_SIN_INTERES', 'Cuotas Sin Interés'), ('CUOTAS_CON_INTERES', 'Cuotas Con Interés')], default='SIN_CUOTAS', max_length=20, null=True, verbose_name='Tipo de Cuotas')),
                ('numero_cuotas', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Cuotas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
